project:
  type: website
  output-dir: docs
  
website:
  title: "amason30.github.io"
  navbar:
    background: primary
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: CV/index.qmd
        text: CV

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full



