- what: Member
  where: U-M Carpentries
  dates: Jan 2023 - Present
- what: Vice President
  where: Microbiology Graduate Student Association
  dates: Aug 2019 - May 2021
- what: Symposium Judge
  where: University of Tennessee Exhibition of Undergraduate Research and Creative Achievement (EUReCA)
  dates: Apr 2020, Apr 2019
- what: Instructor
  where: University of Tennessee KidsU Fun with Forensics, Adventures in Chemistry
  dates: Jul 2019, Jul 2018
- what: Regional Judge
  where: Health Occupations Students of America (HOSA) Ohio Regional
  dates: May 2017
- what: Symposium Judge
  where: Eastland-Fairfield Bioscience Technologies Capstone Symposium
  dates: Apr 2014